
DC= {}
DEMA= {}
Dynamic_Buy_Sell= {}
Elliot= {}
EMA= {}

FastRSI= {}
Fibonacci= {}
Fixed_Buy_Sell= {}
Ichimoku_Clouds= {}
KAMA= {}
Keltner_Channels= {}
Momentum= {}
MFI= {}
MACD= {}
ROC= {}
RS= {}
RSI= {}
SAR= {}
SMA= {}
SlowRSI= {}
Stochastic= {}
Stoch-RSI= {}
Stochastic^2= {}
Timed_Blind= {}
TD= {}
TRIMA= {}
TRIX= {}
TEMA= {}
UO= {}
WMA= {}
Williams_%R= {}
Aroon= {}
Aroon_Oscillator= {}
AO= {}
BOP= {}
Bollinger_Bands= {}
Bollinger_Bands_%B= {}
Bollinger_Bands_%W= {}
Candle_Pattern_finder= {}
CMO= {}
CRSI= {}
Coppock_Curve= {}
DPO= {}

DC["length"] = [2,100,2]
DEMA["short_length"] = [4,21,2]
DEMA["long_length"] = [8,42,2]
DEMA["swing"] = [0,0,0]
Dynamic_Buy_Sell["minutes_before_adjust"] = [20,240,10]
Elliot["lookbacka"] = [5,80,5]
EMA["short_length"] = [4,21,2]
EMAArithmeticError
EMA["swing"] = [0,0,0]
FastRSI["rsi_length"] = [6,30,2]
FastRSI["signal_length"] = [2,10,1]
FastRSI["buy_level"] = [10,45,2]
FastRSI["sell_level"] = [59,81,2]
Fibonacci["buy_price"] = [5,40,2]
Fixed_Buy_Sell["buy_price"] = [0.0,2.5,2]
Fixed_Buy_Sell["sell_price"] = [0.0,2.5,2]
Ichimoku_Clouds["tenkan-sen"] = [6,30,2]
Ichimoku_Clouds["kijun-sen"] = [12,40,2]
Ichimoku_Clouds["senkou_span_b"] = [40,80,2]
Ichimoku_Clouds["chikouspan"] = [26,50,2]
Ichimoku_Clouds["buy_sell_trigger"] = [CloudTwist,CloudBreakOut]
KAMA["short_length"] = [2,20,2]
KAMA["long_length"] = [20,40,2]
Keltner_Channels["sma_length"] = [2,30,2]
Keltner_Channels["multiplier"] = [0.1,2.0,0.2]
Keltner_Channels["atr_length"] = [2,20,2]
Momentum["length"] = [2,20,2]
MFI["length"] = [2,20,2]
MFI["buy_level"] = [10,45_,2]
MFI["sell_level"] = [59,81,2]
MACD["short_length"] = [2,20,2]
MACD["long_length"] = [4,40,2]
MACD["signal_length"] = [2,12,2]
MACD["trigger_method"] = [MACD-Signal_Cross,MACD-Zero_Cross,Signal-Zero_Cross]
ROC["roc"] = [10,40,2]
ROC["buy_threshold"] = [-0.2,-0,05,0.02]
ROC["sell_threshold"] = [0.1,0.3,0.02]
RS["buy_price"] = [10,40,2]
RSI["length"] = [2,21,2]
RSI["buy_level"] = [10,40,2]
RSI["sell_level"] = [60,81,2]
SAR["acceleration"] = [0.02,0.2,0.02]
SAR["maximum2"] = [0.1,0.2,2]
SMA["short_length"] = [2,40,2]
SMA["long_length"] = [4,80,2]
SMA["swing"] = [0.0,0.01,0.001]
SlowRSI["rsi_length"] = [2,40,2]
SlowRSI["signal_length"] = [2,12,2]
SlowRSI["buy_level"] = [10,40,2]
SlowRSI["sell_level"] = [60,81,2]
Stochastic["length"] = [2,40,2]
Stochastic["buy_level"] = [10,40,2]
Stochastic["sell_level"] = [60,81,2]
Stoch-RSI["rsi_length"] = [2,40,2]
Stoch-RSI["fast_k"] = [3,10,2]
Stoch-RSI["fast_d"] = [2,8,2]
Stoch-RSI["buy_level"] = [10,40,2]
Stoch-RSI["sell_level"] = [60,81,2]
Stoch-RSI["trigger_method"] = [Threshold_Cross,Lines_Cross]
Stochastic^2["length"] = [2,20,2]
Stochastic^2["buy_level"] = [10,40,2]
Stochastic^2["sell_level"] = [60,81,2]
Timed_Blind["minutes_before_signal_change"] = [10,200,2]
TD["number_of_candles_for_buy"] = [2,15,2]
TD["lookback_for_buy"] = [4,20,2]
TD["signal_when_buy_sequence_broke"] = [False]
TD["number_of_candles_for_sell"] = [3,18,2]
TD["lookback_for_sell"] = [3,20,2]
TD["signal_when_sell_sequence_broke"] = [False]
TRIMA["short_length"] = [2,20,2]
TRIMA["long_length"] = [4,40,2]
TRIX["length"] = [2,20,2]
TEMA["short_length"] = [2,20,2]
TEMA["long_length"] = [2,40,2]
TEMA["swing"] = [0.0,0.1,0.01]
UO["short_length"] = [2,10,2]
UO["middle_length"] = [5,20,2]
UO["long_length"] = [10,30,2]
WMA["short_length"] = [2,10,2]
WMA["long_length"] = [2,30,2]
WMA["swing"] = [0.0,0.1,0.01]
Williams_%R["length"] = [2,21,2]
Williams_%R["buy_level"] = [-30,-20,2]
Williams_%R["sell_level"] = [-70,-90,2]
Aroon["lookback"] = [10,30,2]
Aroon_Oscillator["lookback"] = [10,30,2]
AO["length-1"] = [5,20,2]
AO["length-2"] = [20,40,2]
AO["buy_threshold"] = [-2,-0.5,2]
AO["sell_threshold"] = [0.5,2,2]
BOP["length"] = [2,to,2]
BOP["buy_threshold"] = [-2,-0.5,2]
BOP["sell_threshold"] = [0.5,2,2]
Bollinger_Bands["length"] = [4,50,2]
Bollinger_Bands["dev.up"] = [0.3,2.1,0.2]
Bollinger_Bands["dev.down"] = [0.3,2.1,0.2]
Bollinger_Bands_%B["length"] = [4,50,2]
Bollinger_Bands_%B["dev.up"] = [0.3,2.1,0.2]
Bollinger_Bands_%B["dev.down"] = [0.3,2.1,0.2]
Bollinger_Bands_%W["length"] = [4,50,2]
Bollinger_Bands_%W["dev.up"] = [0.3,2.1,0.2]
Bollinger_Bands_%W["dev.down"] = [0.3,2.1,0.2]
Bollinger_Bands_%W["buy_level"] = [0.001,0.1,0.01]
Bollinger_Bands_%W["sell_level"] = [0.002,0.2,0.01]
Bollinger_Bands["length"] = [4,50,2]
Bollinger_Bands["dev.up"] = [0.3,2.1,0.2]
Bollinger_Bands["dev.down"] = [0.3,2.1,0.2]
Candle_Pattern_finder["pattern"] = [None,SimpleUpCandle,SimpleDownCandle,SimpleDoubleUpCandle,SimpleDoubleDownCandle,TwoCrows,ThreeBlackCrows,ThreeInsideUp,ThreeInsideDown,ThreeLineStrikeBullish,ThreeLineStrikeBearish,ThreeOutsideUp,ThreeOutsideDown,ThreeStarsInSouth,ThreeStarsInNorth,ThreeWhiteSoldiers,AdvanceBlock,BeltHoldBullish,BeltHoldBearish,BreakawayBullish,BreakawayBearish,ClosingMarubozu,ConcealBabysWall,CounterAttackBullish,CounterAttackBearish,Doji,DojiStar,DragonflyDoji,EngulfingBullish,EngulfingBearish,GapSideSideWhite,GravestoneDoji,Hammer,HangingMan,HaramiBullish,HaramiBearish,HaramiCrossBullish,HaramiCrossBearish,HighWave,HikkakeBullish,HikkakeBearish,HomingPigeon,Identical3Crows,InNeck,InvertedHammer,KickingBearish,KickingBullish,LadderBottom,LongLeggedDoji,LongLine,MarubozuBullish,MarubozuBearish,MatchingLow,OnNeck,Piercing,RickshawMan,RiseFall3Methods,SeperatingLines,ShootingStar,ShortLine,SpinningTop,StalledPattern,StickSandwhichUp,StickSandwhichDown,TasukiGap,Thrusting,Tristar]
CMO["length"] = [2,40,2]
CMO["buy_threshold"] = [-10.0,-2.0,2.0]
CMO["sell_threshold"] = [10.0,2.0_,2.0]
CRSI["length"] = [2,20,2]
CRSI["u_d_length"] = [2,10,2]
CRSI["roc"] = [80,100,2]
CRSI["buy_level"] = [10,30,2]
CRSI["sell_level"] = [70,90,2]
Coppock_Curve["roc-1"] = [6,21,4]
Coppock_Curve["roc-2"] = [14,40,4]
Coppock_Curve["wmalength"] = [2,20,4]
Coppock_Curve["buy_threshold"] = [-0,1,-0.2,-0.02]
Coppock_Curve["sell_threshold"] = [0,1,0.2,0.02]
DPO["short"] = [8,16,2]
DPO["long"] = [19,36,2]
DPO["buy_threshold"] = [-0,1,-0.2,-0.02]
DPO["sell_threshold"] = [0,1,0.2,0.02]