"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""


from setuptools import setup

APP = ['rotator.py']
DATA_FILES = ['config.ini','configparser_cos.py']
APP_NAME = "SuperSandwich"

OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Bruteforcing stuff",
        'CFBundleIdentifier': "com.metachris.osx.sandwich",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2018, Cosmos, All Rights Reserved"
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)