d = {}
all_indicators_full_names = [
    "Aroon",
    "Aroon Oscillator",
    "Awesome Oscillator",
    "Balance of Power (BOP)",
    "Blind indicator",
    "Bollinger Bands",
    "Bollinger Bands %B",
    "Bollinger Bands %W",
    "Bollinger Bands (Legacy)",
    "Candle Pattern finder",
    "Chande Momentum Oscillator (CMO)",
    "Connor RSI (CRSI)",
    "Coppock Curve",
    "Detrended Price Oscillator (DPO)",
    "Donchian Channels",
    "Double Exponential Moving Average (DEMA)",
    "Double Exponential Moving Average (DEMA) (Legacy)",
    "Dynamic adjusting Buy/Sell",
    "Elliott Prediction (Concept)",
    "Exponential Moving Average (EMA)",
    "Exponential Moving Average (EMA) (Legacy)",
    "Fast Moving RSI (FastRSI)",
    "Fibonacci",
    "CCI",
    "Fixed Buy/Sell",
    "Fractal",
    "Ichimoku Clouds",
    "Kaufmans Adaptive Moving Average (KAMA)",
    "Kaufmans Adaptive Moving Average (KAMA) (Legacy)",
    "Keltner Channels",
    "Keltner Channels (Legacy)",
    "Momentum",
    "Money Flow Index (MFI)",
    "Moving Average Convergence/Divergence (MACD)",
    "Moving Average Convergence/Divergence (MACD) (Legacy)",
    "Rate of change (Alternative) (ROC)",
    "Rate of change (ROC)",
    "Regression Slope",
    "Relative Strength Index (RSI)",
    "Relative Strength Index (RSI)(Legacy)",
    "SAR",
    "SARScripted Indicator (C#)",
    "Simple Moving Average (SMA)",
    "Slow Moving RSI (SlowRSI)",
    "Small Fractal",
    "Stochastic",
    "Stochastic Relative Strength Index (Stoch-RSI)",
    "Stochastic Relative Strength Index (Stoch-RSI)(Legacy)",
    "Stochastic^2",
    "Timed Blind indicator",
    "Tom Demark Sequential (TD)",
    "Triangular Moving Average (TRIMA)",
    "Triangular Moving Average (TRIMA)(Legacy)",
    "Triple Exponential Average (TRIX)",
    "Triple Exponential Average (TRIX)(Legacy)",
    "Triple Exponential Moving Average (TEMA)",
    "Triple Exponential Moving Average (TEMA)(Legacy)",
    "Ultimate Oscillator",
    "Ultimate Oscillator (Legacy)",
    "Weighted Moving Average (WMA)",
    "Williams %R",
    "Williams %R (Legacy)",
]

all_indicators_short_names = []

for i in all_indicators_names:
    d[i] = {}
