i = [
    "Aroon",
    "Aroon Oscillator",
    "AO",
    "BOP",
    "Blind indicator",
    "Bollinger Bands",
    "Bollinger Bands %B",
    "Bollinger Bands %W",
    "Bollinger Bands (Legacy)",
    "Candle Pattern finder",
    "CMO",
    "CRSI",
    "Coppock Curve",
    "DPO",
    "DC",
    "DEMA",
    "Dynamic Buy/Sell",
    "Elliot",
    "EMA",
    "FastRSI",
    "Fibonacci",
    "Fixed Buy/Sell",
    "Fractal",
    "Ichimoku Clouds",
    "KAMA",
    "Keltner Channels",
    "Momentum",
    "MFI",
    "MACD",
    "ROC",
    "RS",
    "RSI",
    "SAR",
    "SMA",
    "SlowRSI",
    "Small Fractal",
    "Stochastic",
    "Stoch-RSI",
    "Stochastic^2",
    "Timed Blind",
    "TD",
    "TRIMA",
    "TRIX",
    "TEMA",
    "UO",
    "WMA",
    "Williams %R",
]
for i in i:
    print("if indicator ==" "'" + i + "':\n pass")
